# conda recipe

package:
  name: midas
  version: "1.2.2"

build:
  number: 0
  binary_relocation: True
  preserve_egg_dir: False

source:
  git_url: https://github.com/mjharriso/MIDAS.git
  git_rev: dev/testing

#  fn: testing.zip
#  url: https://github.com/mjharriso/MIDAS/archive/dev/testing.zip

requirements:
  build:
    - python 2.7.11
    - libnetcdf 4.4.1
    - libgfortran 3.0.0
    - libnetcdff 4.4.4
    - hdf5 1.8.17
    - hdf4 4.2.12
    - jpeg 9b
    - numpy 1.10.4
  run:
    - python 2.7.11
    - libnetcdf 4.4.1
    - libnetcdff 4.4.4
    - libgfortran 3.0.0
    - hdf4 4.2.12
    - hdf5 1.8.17
    - jpeg 9b
    - numpy 1.10.4
    - netcdf4 1.2.7
    - scipy 0.17.0
    - basemap 1.0.7
    - dateutil 2.4.1
test:
  imports:
    - midas.rectgrid
    - fms_hinterp
  commands:
    - echo "Testing from the meta.yaml"
    - echo "This is Windows" # [win]
    - echo "This is not Windows" # [not win]
    - echo "This is OSX" # [osx]
    - echo "This is not OSX" # [not osx]

about:
  home: https://github.com/mjharriso/MIDAS
  license: CreativeCommons 3.0
