# conda recipe

package:
  name: midas
  version: "1.2"

build:
  number: 0
  binary_relocation: true
  preserve_egg_dir: True

source:
  git_url: https://github.com/mjharriso/MIDAS.git
  git_rev: dc41431819f4b001b5909b344cac9a79547c52ed

#  fn: testing.zip
#  url: https://github.com/mjharriso/MIDAS/archive/dev/testing.zip

requirements:
  build:
    - python
    - libnetcdf
    - numpy 1.10.4
  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - basemap
    - dateutil
test:
  imports:
    - midas.rectgrid
  commands:
    - echo "Testing from the meta.yaml"
    - echo "This is Windows" # [win]
    - echo "This is not Windows" # [not win]
    - echo "This is OSX" # [osx]
    - echo "This is not OSX" # [not osx]

about:
  home: https://github.com/mjharriso/MIDAS
  license: CreativeCommons 3.0
